name: glanzmann-SCHWIMMEN
favicon: null
layout_spectrum: 0.19150401349179447
typography_spectrum: 0.38865
title: glanzmann-FOTOGRAFIE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4310049023479223
  lightness: 0.17006478807888925
  saturation: 0.2860268047079444
  rhythmicContrast: 0.09558848780579865
purpose: []
